# Generated by Django 3.2.3 on 2023-08-13 18:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddCart',
            new_name='Cart',
        ),
        migrations.RenameModel(
            old_name='Ingridients',
            new_name='Ingridient',
        ),
    ]
